version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data/database.db:/app/data/database.db
    environment:
      - BASE_URL=http://localhost:8080/
      - DATABASE_FILE=data/database.db
      - PORT=8080
#    entrypoint: /app/bin/short
#    command: ls